const categorias = {
    frutas: [
        { clave: "1", src: "assets/cartas/frutas/aguacate.png" },
        { clave: "2", src: "assets/cartas/frutas/albaricoque.png" },
        { clave: "3", src: "assets/cartas/frutas/arandanos.png" },
        { clave: "4", src: "assets/cartas/frutas/caqui.png" },
        { clave: "5", src: "assets/cartas/frutas/cereza.png" },
        { clave: "6", src: "assets/cartas/frutas/Chirimoya.png" },
        { clave: "7", src: "assets/cartas/frutas/ciruela.png" },
        { clave: "8", src: "assets/cartas/frutas/frambuesa.png" },
        { clave: "9", src: "assets/cartas/frutas/fresa.png" },
        { clave: "10", src: "assets/cartas/frutas/granada.png" },
        { clave: "11", src: "assets/cartas/frutas/kiwi.png" },
        { clave: "12", src: "assets/cartas/frutas/lima.png" },
        { clave: "13", src: "assets/cartas/frutas/mandarina.png" },
        { clave: "14", src: "assets/cartas/frutas/mango.png" },
        { clave: "15", src: "assets/cartas/frutas/manzana.png" },
        { clave: "16", src: "assets/cartas/frutas/manzana-verde.png" },
        { clave: "17", src: "assets/cartas/frutas/melocoton.png" },
        { clave: "18", src: "assets/cartas/frutas/melon.png" },
        { clave: "19", src: "assets/cartas/frutas/melon2.png" },
        { clave: "20", src: "assets/cartas/frutas/melon-amarillo.png" },
        { clave: "21", src: "assets/cartas/frutas/Moras.png" },
        { clave: "22", src: "assets/cartas/frutas/naranja.png" },
        { clave: "23", src: "assets/cartas/frutas/papaya.png" },
        { clave: "24", src: "assets/cartas/frutas/paraguaya.png" },
        { clave: "25", src: "assets/cartas/frutas/pera.png" },
        { clave: "26", src: "assets/cartas/frutas/piña.png" },
        { clave: "27", src: "assets/cartas/frutas/platano.png" },
        { clave: "28", src: "assets/cartas/frutas/pomelo.png" },
        { clave: "29", src: "assets/cartas/frutas/sandia.png" },
        { clave: "30", src: "assets/cartas/frutas/tomates.png" },
        { clave: "31", src: "assets/cartas/frutas/tomates-cherry.png" },
        { clave: "32", src: "assets/cartas/frutas/uva.png" }
    ],

    daw: [
        { clave: "1", src: "assets/cartas/daw/Angular.png" },
        { clave: "2", src: "assets/cartas/daw/Apache.png" },
        { clave: "3", src: "assets/cartas/daw/aws.png" },
        { clave: "4", src: "assets/cartas/daw/Bootstrap.png" },
        { clave: "5", src: "assets/cartas/daw/CSS3.png" },
        { clave: "6", src: "assets/cartas/daw/docker.png" },
        { clave: "7", src: "assets/cartas/daw/git.png" },
        { clave: "8", src: "assets/cartas/daw/GitHub.png" },
        { clave: "9", src: "assets/cartas/daw/HTML5.png" },
        { clave: "10", src: "assets/cartas/daw/IntelliJ.png" },
        { clave: "11", src: "assets/cartas/daw/Java.png" },
        { clave: "12", src: "assets/cartas/daw/js.png" },
        { clave: "13", src: "assets/cartas/daw/kali.png" },
        { clave: "14", src: "assets/cartas/daw/Laravel.png" },
        { clave: "15", src: "assets/cartas/daw/linux.png" },
        { clave: "16", src: "assets/cartas/daw/mariadb.png" },
        { clave: "17", src: "assets/cartas/daw/mongodb.png" },
        { clave: "18", src: "assets/cartas/daw/mysql.png" },
        { clave: "19", src: "assets/cartas/daw/Nginx.png" },
        { clave: "20", src: "assets/cartas/daw/oracledb.png" },
        { clave: "21", src: "assets/cartas/daw/PHP.png" },
        { clave: "22", src: "assets/cartas/daw/Postman.png" },
        { clave: "23", src: "assets/cartas/daw/python.png" },
        { clave: "24", src: "assets/cartas/daw/React.png" },
        { clave: "25", src: "assets/cartas/daw/spring-boot.png" },
        { clave: "26", src: "assets/cartas/daw/sql.png" },
        { clave: "27", src: "assets/cartas/daw/sqllite.png" },
        { clave: "28", src: "assets/cartas/daw/Tailwind.png" },
        { clave: "29", src: "assets/cartas/daw/Typescript.png" },
        { clave: "30", src: "assets/cartas/daw/vscode.png" },
        { clave: "31", src: "assets/cartas/daw/wampserver.png" },
        { clave: "32", src: "assets/cartas/daw/xampp.png" }
    ],

    davante: [
        { clave: "1", src: "assets/cartas/davante/Alicante.png" },
        { clave: "2", src: "assets/cartas/davante/arboles.png" },
        { clave: "3", src: "assets/cartas/davante/Davante_fundacion_horiz_navy.png" },
        { clave: "4", src: "assets/cartas/davante/Davante_logo_claim_navy.png" },
        { clave: "5", src: "assets/cartas/davante/Davante_logo_claim_white.png" },
        { clave: "6", src: "assets/cartas/davante/Davante_logo_endosos_navy.png" },
        { clave: "7", src: "assets/cartas/davante/Davante_logo_endosos_white.png" },
        { clave: "8", src: "assets/cartas/davante/Davante_logo_fundacion_horiz_white.png" },
        { clave: "9", src: "assets/cartas/davante/Davante_logo_fundacion_vert_navy.png" },
        { clave: "10", src: "assets/cartas/davante/Davante_logo_fundacion_vert_white.png" },
        { clave: "11", src: "assets/cartas/davante/Davante_logo_tagline_navy.png" },
        { clave: "12", src: "assets/cartas/davante/Davante_logo_tagline_white.png" },
        { clave: "13", src: "assets/cartas/davante/Davante_logotipo_black.png" },
        { clave: "14", src: "assets/cartas/davante/Davante_logotipo_navy.png" },
        { clave: "15", src: "assets/cartas/davante/Davante_logotipo_white.png" },
        { clave: "16", src: "assets/cartas/davante/Davante_simbolo_navy.png" },
        { clave: "17", src: "assets/cartas/davante/Davante_simbolo_orange.png" },
        { clave: "18", src: "assets/cartas/davante/Davante_simbolo_white.png" },
        { clave: "19", src: "assets/cartas/davante/Ejido.png" },
        { clave: "20", src: "assets/cartas/davante/madrid.png" },
        { clave: "21", src: "assets/cartas/davante/malaga.png" },
        { clave: "22", src: "assets/cartas/davante/medac.png" },
        { clave: "23", src: "assets/cartas/davante/medac_fondo_blanco.png" },
        { clave: "24", src: "assets/cartas/davante/MEDAC_imagotipo_horiz_tagline_azul_PNG.png" },
        { clave: "25", src: "assets/cartas/davante/MEDAC_logo.png" },
        { clave: "26", src: "assets/cartas/davante/medac100.png" },
        { clave: "27", src: "assets/cartas/davante/Tablero_Digitalización.png" },
        { clave: "28", src: "assets/cartas/davante/Tablero_Entornos.png" },
        { clave: "29", src: "assets/cartas/davante/Tablero_FOL.png" },
        { clave: "30", src: "assets/cartas/davante/Tablero_Lenguaje.png" },
        { clave: "31", src: "assets/cartas/davante/Tablero_Programación.png" },
        { clave: "32", src: "assets/cartas/davante/valencia.png" }
    ]
};
