// CAMBIAR POR LAS CATEGORIAS DEFINITIVAS (MEDAC, DAW Y LO QUE HABIAMOS PENSADO)
const categorias = {
    frutas: [
        { clave: "manzana", src: "assets/cartas/frutas/manzana.webp" },
        { clave: "platano", src: "assets/cartas/frutas/platano.webp" },
        { clave: "fresa", src: "assets/cartas/frutas/fresa.png" },
        { clave: "piña", src: "assets/cartas/frutas/piña.png" },
        { clave: "naranja", src: "assets/cartas/frutas/naranja.webp" },
        { clave: "sandia", src: "assets/cartas/frutas/sandia.png" },
        { clave: "uva", src: "assets/cartas/frutas/uva.webp" },
        { clave: "kiwi", src: "assets/cartas/frutas/kiwi.webp" }
    ],
    numeros: [
        { clave: "1", src: "assets/cartas/numeros/1.png" },
        { clave: "2", src: "assets/cartas/numeros/2.png" },
        { clave: "3", src: "assets/cartas/numeros/3.png" },
        { clave: "4", src: "assets/cartas/numeros/4.png" },
        { clave: "5", src: "assets/cartas/numeros/5.png" },
        { clave: "6", src: "assets/cartas/numeros/6.png" },
        { clave: "7", src: "assets/cartas/numeros/7.png" },
        { clave: "8", src: "assets/cartas/numeros/8.png" },
        { clave: "9", src: "assets/cartas/numeros/9.png" },
        { clave: "10", src: "assets/cartas/numeros/10.png" },
        { clave: "11", src: "assets/cartas/numeros/11.png" },
        { clave: "12", src: "assets/cartas/numeros/12.png" },
        { clave: "13", src: "assets/cartas/numeros/13.png" },
        { clave: "14", src: "assets/cartas/numeros/14.png" },
        { clave: "15", src: "assets/cartas/numeros/15.png" },
        { clave: "16", src: "assets/cartas/numeros/16.png" },
        { clave: "17", src: "assets/cartas/numeros/17.png" },
        { clave: "18", src: "assets/cartas/numeros/18.png" },
        { clave: "18", src: "assets/cartas/numeros/1.png" },
        { clave: "20", src: "assets/cartas/numeros/2.png" },
        { clave: "21", src: "assets/cartas/numeros/3.png" },
        { clave: "22", src: "assets/cartas/numeros/4.png" },
        { clave: "23", src: "assets/cartas/numeros/5.png" },
        { clave: "24", src: "assets/cartas/numeros/6.png" },
        { clave: "25", src: "assets/cartas/numeros/7.png" },
        { clave: "26", src: "assets/cartas/numeros/8.png" },
        { clave: "27", src: "assets/cartas/numeros/9.png" },
        { clave: "28", src: "assets/cartas/numeros/10.png" },
        { clave: "29", src: "assets/cartas/numeros/11.png" },
        { clave: "30", src: "assets/cartas/numeros/12.png" },
        { clave: "31", src: "assets/cartas/numeros/13.png" },
        { clave: "32", src: "assets/cartas/numeros/14.png" },
        { clave: "33", src: "assets/cartas/numeros/15.png" },
        { clave: "34", src: "assets/cartas/numeros/16.png" },
        { clave: "35", src: "assets/cartas/numeros/17.png" },
        { clave: "36", src: "assets/cartas/numeros/18.png" }
    ],
    davante: [
        { clave: "1", src: "assets/cartas/davante/Davante_fundacion_horiz_navy.png" },
        { clave: "2", src: "assets/cartas/davante/Davante_logo_claim_navy.png" },
        { clave: "3", src: "assets/cartas/davante/Davante_logo_claim_white.png" },
        { clave: "4", src: "assets/cartas/davante/Davante_logo_fundacion_horiz_white.png" },
        { clave: "5", src: "assets/cartas/davante/Davante_logo_fundacion_vert_navy.png" },
        { clave: "6", src: "assets/cartas/davante/Davante_logo_fundacion_vert_white.png" },
        { clave: "7", src: "assets/cartas/davante/Davante_logo_tagline_navy.png" },
        { clave: "8", src: "assets/cartas/davante/Davante_logo_tagline_white.png" },
        { clave: "9", src: "assets/cartas/davante/Davante_logotipo_black.png" },
        { clave: "10", src: "assets/cartas/davante/Davante_logotipo_navy.png" },
        { clave: "11", src: "assets/cartas/davante/Davante_logotipo_white.png" },
        { clave: "12", src: "assets/cartas/davante/Davante_simbolo_navy.png" },
        { clave: "13", src: "assets/cartas/davante/Davante_simbolo_orange.png" },
        { clave: "14", src: "assets/cartas/davante/Davante_simbolo_white.png" },
        { clave: "15", src: "assets/cartas/davante/medac.png" },
        { clave: "16", src: "assets/cartas/davante/medac_fondo_blanco.png" },
        { clave: "17", src: "assets/cartas/davante/MEDAC_imagotipo_horiz_tagline_azul_PNG.png" },
        { clave: "18", src: "assets/cartas/davante/MEDAC_logo.png" }
    ]
    
};
